import { InMemoryDbService } from 'angular-in-memory-web-api';
declare var require: any;

export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const cards = [
      {id:  1 , image: require('../../png/10_of_clubs.png')        , name: '10_of_clubs'      },
      {id:  2 , image: require('../../png/10_of_diamonds.png')     , name: '10_of_diamonds'   },       
      {id:  3 , image: require('../../png/10_of_hearts.png')       , name: '10_of_hearts'     },      
      {id:  4 , image: require('../../png/10_of_spades.png')       , name: '10_of_spades'     },  
      {id:  5 , image: require('../../png/2_of_clubs.png')         , name: '2_of_clubs'       }, 
      {id:  6 , image: require('../../png/2_of_diamonds.png')      , name: '2_of_diamonds'    },      
      {id:  7 , image: require('../../png/2_of_hearts.png')        , name: '2_of_hearts'      },    
      {id:  8 , image: require('../../png/2_of_spades.png')        , name: '2_of_spades'      },    
      {id:  9 , image: require('../../png/3_of_clubs.png')         , name: '3_of_clubs'       },    
      {id: 10 , image: require('../../png/3_of_diamonds.png')      , name: '3_of_diamonds'    },       
      {id: 11 , image: require('../../png/3_of_hearts.png')        , name: '3_of_hearts'      },   
      {id: 12 , image: require('../../png/3_of_spades.png')        , name: '3_of_spades'      },     
      {id: 13 , image: require('../../png/4_of_clubs.png')         , name: '4_of_clubs'       },     
      {id: 14 , image: require('../../png/4_of_diamonds.png')      , name: '4_of_diamonds'    },      
      {id: 15 , image: require('../../png/4_of_hearts.png')        , name: '4_of_hearts'      },    
      {id: 16 , image: require('../../png/4_of_spades.png')        , name: '4_of_spades'      },     
      {id: 17 , image: require('../../png/5_of_clubs.png')         , name: '5_of_clubs'       },   
      {id: 18 , image: require('../../png/5_of_diamonds.png')      , name: '5_of_diamonds'    },       
      {id: 19 , image: require('../../png/5_of_hearts.png')        , name: '5_of_hearts'      },      
      {id: 20 , image: require('../../png/5_of_spades.png')        , name: '5_of_spades'      },     
      {id: 21 , image: require('../../png/6_of_clubs.png')         , name: '6_of_clubs'       },    
      {id: 22 , image: require('../../png/6_of_diamonds.png')      , name: '6_of_diamonds'    },         
      {id: 23 , image: require('../../png/6_of_hearts.png')        , name: '6_of_hearts'      },   
      {id: 24 , image: require('../../png/6_of_spades.png')        , name: '6_of_spades'      },   
      {id: 25 , image: require('../../png/7_of_clubs.png')         , name: '7_of_clubs'       },    
      {id: 26 , image: require('../../png/7_of_diamonds.png')      , name: '7_of_diamonds'    },     
      {id: 27 , image: require('../../png/7_of_hearts.png')        , name: '7_of_hearts'      },    
      {id: 28 , image: require('../../png/7_of_spades.png')        , name: '7_of_spades'      },   
      {id: 29 , image: require('../../png/8_of_clubs.png')         , name: '8_of_clubs'       },   
      {id: 30 , image: require('../../png/8_of_diamonds.png')      , name: '8_of_diamonds'    },     
      {id: 31 , image: require('../../png/8_of_hearts.png')        , name: '8_of_hearts'      },     
      {id: 32 , image: require('../../png/8_of_spades.png')        , name: '8_of_spades'      },     
      {id: 33 , image: require('../../png/9_of_clubs.png')         , name: '9_of_clubs'       },    
      {id: 34 , image: require('../../png/9_of_diamonds.png')      , name: '9_of_diamonds'    },     
      {id: 35 , image: require('../../png/9_of_hearts.png')        , name: '9_of_hearts'      },    
      {id: 36 , image: require('../../png/9_of_spades.png')        , name: '9_of_spades'      },     
      {id: 37 , image: require('../../png/ace_of_clubs.png')       , name: 'ace_of_clubs'     },     
      {id: 38 , image: require('../../png/ace_of_diamonds.png')    , name: 'ace_of_diamonds'  },     
      {id: 39 , image: require('../../png/ace_of_hearts.png')      , name: 'ace_of_hearts'    },    
      {id: 40 , image: require('../../png/ace_of_spades.png')      , name: 'ace_of_spades'    },    
      {id: 41 , image: require('../../png/black_joker.png')        , name: 'black_joker'      },   
      {id: 42 , image: require('../../png/jack_of_clubs.png')      , name: 'jack_of_clubs'    },      
      {id: 43 , image: require('../../png/jack_of_diamonds.png')   , name: 'jack_of_diamonds' },      
      {id: 44 , image: require('../../png/jack_of_hearts.png')     , name: 'jack_of_hearts'   },    
      {id: 45 , image: require('../../png/jack_of_spades.png')     , name: 'jack_of_spades'   },    
      {id: 46 , image: require('../../png/king_of_clubs.png')      , name: 'king_of_clubs'    },    
      {id: 47 , image: require('../../png/king_of_diamonds.png')   , name: 'king_of_diamonds' },     
      {id: 48 , image: require('../../png/king_of_hearts.png')     , name: 'king_of_hearts'   },  
      {id: 49 , image: require('../../png/king_of_spades.png')     , name: 'king_of_spades'   },    
      {id: 50 , image: require('../../png/queen_of_clubs.png')     , name: 'queen_of_clubs'   },   
      {id: 51 , image: require('../../png/queen_of_diamonds.png')  , name: 'queen_of_diamonds'},   
      {id: 52 , image: require('../../png/queen_of_hearts.png')    , name: 'queen_of_hearts'  },  
      {id: 53 , image: require('../../png/queen_of_spades.png')    , name: 'queen_of_spades'  }, 
      {id: 54 , image: require('../../png/red_joker.png')          , name: 'red_joker'        }
    ];
    return {cards};
  }
}
