import { InMemoryDbService } from 'angular-in-memory-web-api';
declare var require: any;

export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const cards = [
      {id:  1 , owner: '' , image: require('../../png/10_of_clubs.png')        , name: '10\u00A0of\u00A0clubs'      },
      {id:  2 , owner: '' , image: require('../../png/10_of_diamonds.png')     , name: '10\u00A0of\u00A0diamonds'   },       
      {id:  3 , owner: '' , image: require('../../png/10_of_hearts.png')       , name: '10\u00A0of\u00A0hearts'     },      
      {id:  4 , owner: '' , image: require('../../png/10_of_spades.png')       , name: '10\u00A0of\u00A0spades'     },  
      {id:  5 , owner: '' , image: require('../../png/2_of_clubs.png')         , name: '2\u00A0of\u00A0clubs'       }, 
      {id:  6 , owner: '' , image: require('../../png/2_of_diamonds.png')      , name: '2\u00A0of\u00A0diamonds'    },      
      {id:  7 , owner: '' , image: require('../../png/2_of_hearts.png')        , name: '2\u00A0of\u00A0hearts'      },    
      {id:  8 , owner: '' , image: require('../../png/2_of_spades.png')        , name: '2\u00A0of\u00A0spades'      },    
      {id:  9 , owner: '' , image: require('../../png/3_of_clubs.png')         , name: '3\u00A0of\u00A0clubs'       },    
      {id: 10 , owner: '' , image: require('../../png/3_of_diamonds.png')      , name: '3\u00A0of\u00A0diamonds'    },       
      {id: 11 , owner: '' , image: require('../../png/3_of_hearts.png')        , name: '3\u00A0of\u00A0hearts'      },   
      {id: 12 , owner: '' , image: require('../../png/3_of_spades.png')        , name: '3\u00A0of\u00A0spades'      },     
      {id: 13 , owner: '' , image: require('../../png/4_of_clubs.png')         , name: '4\u00A0of\u00A0clubs'       },     
      {id: 14 , owner: '' , image: require('../../png/4_of_diamonds.png')      , name: '4\u00A0of\u00A0diamonds'    },      
      {id: 15 , owner: '' , image: require('../../png/4_of_hearts.png')        , name: '4\u00A0of\u00A0hearts'      },    
      {id: 16 , owner: '' , image: require('../../png/4_of_spades.png')        , name: '4\u00A0of\u00A0spades'      },     
      {id: 17 , owner: '' , image: require('../../png/5_of_clubs.png')         , name: '5\u00A0of\u00A0clubs'       },   
      {id: 18 , owner: '' , image: require('../../png/5_of_diamonds.png')      , name: '5\u00A0of\u00A0diamonds'    },       
      {id: 19 , owner: '' , image: require('../../png/5_of_hearts.png')        , name: '5\u00A0of\u00A0hearts'      },      
      {id: 20 , owner: '' , image: require('../../png/5_of_spades.png')        , name: '5\u00A0of\u00A0spades'      },     
      {id: 21 , owner: '' , image: require('../../png/6_of_clubs.png')         , name: '6\u00A0of\u00A0clubs'       },    
      {id: 22 , owner: '' , image: require('../../png/6_of_diamonds.png')      , name: '6\u00A0of\u00A0diamonds'    },         
      {id: 23 , owner: '' , image: require('../../png/6_of_hearts.png')        , name: '6\u00A0of\u00A0hearts'      },   
      {id: 24 , owner: '' , image: require('../../png/6_of_spades.png')        , name: '6\u00A0of\u00A0spades'      },   
      {id: 25 , owner: '' , image: require('../../png/7_of_clubs.png')         , name: '7\u00A0of\u00A0clubs'       },    
      {id: 26 , owner: '' , image: require('../../png/7_of_diamonds.png')      , name: '7\u00A0of\u00A0diamonds'    },     
      {id: 27 , owner: '' , image: require('../../png/7_of_hearts.png')        , name: '7\u00A0of\u00A0hearts'      },    
      {id: 28 , owner: '' , image: require('../../png/7_of_spades.png')        , name: '7\u00A0of\u00A0spades'      },   
      {id: 29 , owner: '' , image: require('../../png/8_of_clubs.png')         , name: '8\u00A0of\u00A0clubs'       },   
      {id: 30 , owner: '' , image: require('../../png/8_of_diamonds.png')      , name: '8\u00A0of\u00A0diamonds'    },     
      {id: 31 , owner: '' , image: require('../../png/8_of_hearts.png')        , name: '8\u00A0of\u00A0hearts'      },     
      {id: 32 , owner: '' , image: require('../../png/8_of_spades.png')        , name: '8\u00A0of\u00A0spades'      },     
      {id: 33 , owner: '' , image: require('../../png/9_of_clubs.png')         , name: '9\u00A0of\u00A0clubs'       },    
      {id: 34 , owner: '' , image: require('../../png/9_of_diamonds.png')      , name: '9\u00A0of\u00A0diamonds'    },     
      {id: 35 , owner: '' , image: require('../../png/9_of_hearts.png')        , name: '9\u00A0of\u00A0hearts'      },    
      {id: 36 , owner: '' , image: require('../../png/9_of_spades.png')        , name: '9\u00A0of\u00A0spades'      },     
      {id: 37 , owner: '' , image: require('../../png/ace_of_clubs.png')       , name: 'ace\u00A0of\u00A0clubs'     },     
      {id: 38 , owner: '' , image: require('../../png/ace_of_diamonds.png')    , name: 'ace\u00A0of\u00A0diamonds'  },     
      {id: 39 , owner: '' , image: require('../../png/ace_of_hearts.png')      , name: 'ace\u00A0of\u00A0hearts'    },    
      {id: 40 , owner: '' , image: require('../../png/ace_of_spades.png')      , name: 'ace\u00A0of\u00A0spades'    },    
      {id: 41 , owner: '' , image: require('../../png/black_joker.png')        , name: 'black\u00A0joker'           },   
      {id: 42 , owner: '' , image: require('../../png/jack_of_clubs.png')      , name: 'jack\u00A0of\u00A0clubs'    },      
      {id: 43 , owner: '' , image: require('../../png/jack_of_diamonds.png')   , name: 'jack\u00A0of\u00A0diamonds' },      
      {id: 44 , owner: '' , image: require('../../png/jack_of_hearts.png')     , name: 'jack\u00A0of\u00A0hearts'   },    
      {id: 45 , owner: '' , image: require('../../png/jack_of_spades.png')     , name: 'jack\u00A0of\u00A0spades'   },    
      {id: 46 , owner: '' , image: require('../../png/king_of_clubs.png')      , name: 'king\u00A0of\u00A0clubs'    },    
      {id: 47 , owner: '' , image: require('../../png/king_of_diamonds.png')   , name: 'king\u00A0of\u00A0diamonds' },     
      {id: 48 , owner: '' , image: require('../../png/king_of_hearts.png')     , name: 'king\u00A0of\u00A0hearts'   },  
      {id: 49 , owner: '' , image: require('../../png/king_of_spades.png')     , name: 'king\u00A0of\u00A0spades'   },    
      {id: 50 , owner: '' , image: require('../../png/queen_of_clubs.png')     , name: 'queen\u00A0of\u00A0clubs'   },   
      {id: 51 , owner: '' , image: require('../../png/queen_of_diamonds.png')  , name: 'queen\u00A0of\u00A0diamonds'},   
      {id: 52 , owner: '' , image: require('../../png/queen_of_hearts.png')    , name: 'queen\u00A0of\u00A0hearts'  },  
      {id: 53 , owner: '' , image: require('../../png/queen_of_spades.png')    , name: 'queen\u00A0of\u00A0spades'  }, 
      {id: 54 , owner: '' , image: require('../../png/red_joker.png')          , name: 'red\u00A0joker'             }
    ];
    return {cards};
  }
}
